* HTML & CSS Assignment: Goal
This is an assignment for [[http://digital.hackinghistory.ca][Digital History]], a digital humanities course taught in the History Department at the University of Toronto.  If you're a teacher, feel free to fork and repurpose for your own courses.  If you're a student, keep reading!

You do not have to become a coder to do well in this course.  However, you /will/ have to be willing to explore technical skills that you might not otherwise develop as a humanities scholar.  In this assignment, you will learn /very basic/ web coding skills and apply them to a simple problem. The goal of the assignment is to provide you with basic technical knowledge that you will need for later assignments.  

* Expectations
This assignment is graded pass/fail. You will only get credit if *all of your code runs as required.* To pass the assignment, you must:
- successfully fork this repository and clone a local copy
- complete all three parts of this assignment, such that both the student-visible tests and the instructor/machine-visible tests all pass.  See below for details but please note that Part 1 includes some work which is to be done on the [[https://codecademy.com/][Codecademy]] website
- commit your work to git as you go, so that a query of the git history will show multiple steps. Please note that git commits are timestamped and unique; they are an excellent defense against accusations of cheating, so please use them extensively.
- push all your changes to github
- submit your assignment via Github Pull Request

* Details

Create a fork of this repository by [[https://classroom.github.com/a/y1HlCM6k][following this link]].  Clone locally via the "Clone or Download" process discussed in [[https://github.com/DigitalHistory/Github][your previous assignment]] and [[https://help.github.com/articles/cloning-a-repository/][described here]], and do your work in Atom. 

Web pages are composed of three components:  HTML, CSS, and Javascript.  HTML provides the /structure and content/ of a web page; CSS controls the /style of presentation/; and Javascript permits /dynamic modification/ of both.  In this assignment, we explore the first two components, HTML and CSS 

*** Problem 1: Codecademy.com
Codeacademy.com is a platform that focusses on teaching web skills; [[http://www.codecademy.com/][head over there and set up an account]]. Once you've done that, simply complete the [[http://www.codecademy.com/tracks/web][HTML & CSS]] course.

When you have finished this course, find the link to your /achievements page/. This page should have a URL with the structure ~https://www.codecademy.com/users/YOURCODECADEMYUSERNAME/achievements~. You can also get to this address by clicking "view my profile under the top right menu item with your picture on it, and from that page clicking "Badges".

Embed a link to this page in the file [[./Part1/index.html]].  You may add any other content if you wish, but this link must exist and point to your unique profile.  

*** Problem 2: Blog Post Content
In this exercise, you will write a short blog post (approximately 200 words) in HTML about a real historical figure about whom you already ave some interest, and in whom you are genuinely interested. You will write this post in [[./Part2/index.html]].  The post should contain, at a minimum, the following elements:
- an ~<article>~ tag, which contains all of the elements mentioned below
- a ~<header>~ element, inside of which there should also be:
  - an ~<h1>~ element with the figure's name
  - an ~<h2>~ element containing the text ~by <span class="author">Your Name</span>~, and also containing *the original ~<a>~ link from Problem 1 that points to your profile*. 
- a ~<section>~ element with class ~main~, containing your main content
- an ~<img>~ or ~<figure>~ tag *within* the main section. The image should be a picture of the historical figure.
- a ~<section>~ element with class ~sources~
- inside your sources section, a ~<ul>~ element containing at least two ~<li>~ elements, each of which lists one source that you used in writing your blog post. The title of the source should bea hyperlink with ~href~ attribute linking back to the source. If your source is a print book or article, the link should point to the source's listing in the library catalog. In the extremely unlikely event that the source is not among the library's holdings, use an Amazon or Google Scholar link instead.  
- steal from [[https://canvas.uw.edu/courses/1118282/assignments/3818107][joel's exercise 01]]
- has to add some html about a historical character
*** Problem 3: Blog Post Styling
In this exercise, you will add style information to your post. You should write the style information in [[./Part2/style.css]]. You may make as many changes as you like, but at a minimum you should:
- add a ~<link.../>~ element to ~<head>~ in ~index.html~, with attributes ~rel~ set to "stylesheet" and ~href~ set to "./style.css"
- set the ~width~ of the ~<header>~ element to "100%
- set the background color of ~<header>~ to something *different from* the background color of the rest of the page
- add right and left margins to ~section.main~ and ~section.sources~
- Add a border to ~section.sources~ to set it off from ~section.main~
- use ~float~ to position the ~img~ or ~figure~ tag *either* on the right or the left of the section
*** Problem 4: Accessibility (required for "A" bundle only)
So far, we have only covered very basic HTML and CSS.  In this problem you are asked to teach yourself about an advanced topic and apply your new knowledge to your web page. In the design of any real website, accessibility to users with visual or other disabilities is very important.  Make sure your web page is fully accessible by adding the following elements to the page:
- metadata tags?
- alt tag (if img); figcaption (if figure)
- aria tags (to what?)
** COMMENT Part 2 - Javascript in the Console  
For Javascript, we will use the excellent online book [[http://eloquentjavascript.net/][Eloquent Javascript]] as a textbook. Read Chapters 1-4 and, importantly, *do all the exercises* using [[http://eloquentjavascript.net/code/][the code sandbox]]. Some of the discussion, especially in chapter 3, may be hard to follow. The exercises may also be quite hard. It is fair to give up and look at the solutions; but be sure you understand the solutions once you've looked at them.

Let me stress this strongly: you almost certainly will not be able to do the exercises without doing the reading.  

Once you have read the textbook and done the exercises, you should find this part of the assignment very straightforward. Complete the code in ~skeleton.js~ according to the instructions in that file.  Check your code by testing it in the [[http://eloquentjavascript.net/code/][EJ code sandbox]], [[https://developer.mozilla.org/en/docs/Tools/Scratchpad][Firefox Scratchpad]], or the [[https://developers.google.com/web/tools/chrome-devtools/debug/console/][Chrome console]].  I have written tests for you which will produce the appropriate output when your code is correct.  

** COMMENT Part 3 - Javascript in the Browser
Continue to read /Eloquent Javascript/, this time chapters [[http://www.eloquentjavascript.net/12_browser.html][12]] and [[http://eloquentjavascript.net/13_dom.html][13]]. Again, read the chapters and do the exercises; if the exercises are too hard, look at the answers but *be sure you understand them*.  

[[./index.html]] is a very simple html file that contains a table of prime ministers.  Your task is write one or more functions that will *add links to the Wikipedia pages of all the prime ministers*.  

Look at the structure of the table. Each row looks like this:

#+BEGIN_SRC html
      <tr>
        <td class="PM">John Sparrow David Thompson</td>
        <td class="Party">Conservative</td>
        <td class="From">1892</td>
        <td class="To">1894</td>
      </tr>
#+END_SRC

Your code should change that to this:
#+BEGIN_SRC html
      <tr>
        <td class="PM"><a href="https://en.wikipedia.org/wiki/John_Sparrow_David_Thompson">John Sparrow David Thompson</a></td>
        <td class="Party">Conservative</td>
        <td class="From">1892</td>
        <td class="To">1894</td>
      </tr>

#+END_SRC

Rather than asking you to include your code directly in ~index.html~, I have provided a script tag at the end of the file which loads the file ~ministers.js~.  There is some template code in that file already; complete the template and test your code by (re)loading index.html in your browser.

I myself will test your code by loading the page and clicking on the links.  They should all point to Wikipedia pages.

*Hints:* In this exercise we are beginning to actually do a form of digital history. Notice that we are treating /text/ as /data/: transforming names into "pointers" that give us access to further information.  

This is made possible because the webpage itself is already well-structured.  Notice the class attribute on each ~<td>~ element:
#+BEGIN_SRC html
<td class="PM">John Sparrow David Thompson</td>
#+END_SRC

Now, consider the structure of Wikipedia links:

#+BEGIN_SRC html
https://en.wikipedia.org/wiki/John_Sparrow_David_Thompson
#+END_SRC

Note they always consist of "https://en.Wikipedia.org/wiki/" + A_Name_With_Spaces_Replaced_By_Underscores.  But, lucky you, /Wikipedia will rewrite spaces as underscores for you!/ If you would like to try to do that part yourself, take a look at [[http://www.w3schools.com/jsref/jsref_replace.asp][the Javascript string replace method]].  

We will use skills developed in the exercises from chapter 13. Your function will have to:
- /find and collect/ all the elements with the class "PM". The method you will need to use is mentioned only once in chapter 13, under "Finding Elements."
- /clear/ the existing text node.
- /add a child node/ of type "a" with text content that comes from the original content, and a link that is constructed of the Wikipedia address prefix + the original content.  

If you find this is too easy: wikify *all* the fields in each row.  Now click on the "party" links. What could you do to fix them? Also, can you change the background color of one or more classes? 

*One more challenge for the eager.* Right now, the wiki links are added immediately when the page loads. Can you defer adding the links until a button is clicked? You will need to add a button element with an "onClick" attribute to index.html, and move the /execution/ of "linkifyClass" out of link-ministers.js.  

P.S. -- you may find it useful or interesting to look at the script I used to generate the table. You will find it in [[./make-minister-table.js]]

* Handing in

As mentioned above: when you are finished -- when your code passes all the tests -- submit your code via pull request.  This is the only acceptable submission process!
